import type { DocTypeDef } from "./types";

export const DOC_TYPES: Record<string, DocTypeDef> = {
  purchase_order: {
    id: "purchase_order", label: "Purchase order", code: "PO",
    destination: "ERP — Orders", destinationCode: "ERP", accent: "cyan",
    minutesManual: 5,
    riskLine: "A wrong quantity ships the wrong pallet count and the customer short-pays.",
    fields: [
      { key: "customer",   label: "Customer",     required: true,  type: "text" },
      { key: "po_number",  label: "PO number",    required: true,  type: "text" },
      { key: "sku",        label: "SKU",          required: true,  type: "text" },
      { key: "quantity",   label: "Quantity",     required: true,  type: "number" },
      { key: "unit_price", label: "Unit price",   required: true,  type: "money" },
      { key: "required_by",label: "Required by",  required: true,  type: "date" },
      { key: "ship_to",    label: "Ship to",      required: false, type: "text" },
      { key: "contact",    label: "Contact",      required: false, type: "text" },
    ],
  },
  supplier_invoice: {
    id: "supplier_invoice", label: "Supplier invoice", code: "INV",
    destination: "Accounting — AP", destinationCode: "AP", accent: "violet",
    minutesManual: 6,
    riskLine: "An invoice with no PO cannot be three-way matched. That is how duplicates get paid.",
    fields: [
      { key: "vendor",     label: "Vendor",       required: true,  type: "text" },
      { key: "invoice_no", label: "Invoice no.",  required: true,  type: "text" },
      { key: "po_ref",     label: "PO reference", required: true,  type: "text" },
      { key: "amount",     label: "Amount",       required: true,  type: "money" },
      { key: "invoice_date",label:"Invoice date", required: true,  type: "date" },
      { key: "due_date",   label: "Due date",     required: false, type: "date" },
      { key: "terms",      label: "Terms",        required: false, type: "text" },
      { key: "description",label: "Description",  required: false, type: "text" },
    ],
  },
  delivery_booking: {
    id: "delivery_booking", label: "Delivery booking", code: "BKG",
    destination: "WMS — Dock schedule", destinationCode: "WMS", accent: "amber",
    minutesManual: 4,
    riskLine: "A missed dock slot means a truck waiting and a detention charge.",
    fields: [
      { key: "carrier",    label: "Carrier",      required: true,  type: "text" },
      { key: "dock_date",  label: "Dock date",    required: true,  type: "date" },
      { key: "dock_time",  label: "Time window",  required: true,  type: "text" },
      { key: "pallets",    label: "Pallets",      required: true,  type: "number" },
      { key: "site",       label: "Site",         required: true,  type: "text" },
      { key: "ref",        label: "Reference",    required: false, type: "text" },
      { key: "driver",     label: "Driver",       required: false, type: "text" },
      { key: "vehicle",    label: "Vehicle",      required: false, type: "text" },
    ],
  },
  quote_request: {
    id: "quote_request", label: "Quote request", code: "RFQ",
    destination: "CRM — Opportunities", destinationCode: "CRM", accent: "emerald",
    minutesManual: 4,
    riskLine: "A quote sent on a misread volume is a margin loss you find out about at invoicing.",
    fields: [
      { key: "company",    label: "Company",      required: true,  type: "text" },
      { key: "product",    label: "Product",      required: true,  type: "text" },
      { key: "volume",     label: "Volume",       required: true,  type: "number" },
      { key: "delivery_to",label: "Deliver to",   required: true,  type: "text" },
      { key: "needed_by",  label: "Needed by",    required: true,  type: "date" },
      { key: "contact",    label: "Contact",      required: false, type: "text" },
      { key: "email",      label: "Email",        required: false, type: "text" },
      { key: "notes",      label: "Notes",        required: false, type: "text" },
    ],
  },
  unclassified: {
    id: "unclassified", label: "Unclassified", code: "—",
    destination: "None", destinationCode: "—", accent: "slate",
    minutesManual: 1, riskLine: "",
    fields: [],
  },
};
